spring.application.name=EventService
# EventService configuration
server.port=8088

# Database configuration for MongoDB (specific to EventService)
spring.data.mongodb.uri=mongodb://mongo:27017/event_service_db
